# local ìš© Spring Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:45432/member
    username: member
    password: welcome
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    validate-migration-naming: true
    schemas: member
    default-schema: member
server:
  port: 3004
