# local ìš© Spring Profile
spring:
  config:
    activate:
      on-profile: local
  mvc:
    static-path-pattern: /content/v1/public/**
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/content
    username: content
    password: welcome
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    validate-migration-naming: true
    schemas: content
    default-schema: content
server:
  port: 3002