spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      unit-test:
        - common
      prod:
        - common
  config:
    import:
      - classpath:config/whitelist.yaml
logging:
  level:
    root: info

---
# 공통
spring:
  config:
    activate:
      on-profile: common
server:
  port: 3000