name: deploy
description: "Deploy Services"

inputs:
  target:
    description: "Gradle Build Target"
    required: true

runs:
  using: "composite"
  steps:
    - name: TEST
      run: |
        echo "test..."