name: Deploy Workflow

inputs:
  target:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Docker Build (${{ inputs.target }})
      run: |
        cd .github/docker
        ./package.sh ${{ inputs.target }} develop ${{ github.run_number }}
      shell: bash

    - name: Docker Push (${{ inputs.target }})
      run: |
        docker push monty082/backend-api-server:${{ inputs.target }}-latest
        docker push monty082/backend-api-server:${{ inputs.target }}-${{ github.run_number }}
      shell: bash