services:
  auth_local_database:
    platform: linux/x86_64
    image: mysql:8.0
    hostname: auth_local_database
    container_name: auth_local_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    ports:
      - "13306:3306"
    volumes:
      - ./database/schema_initialisation.sql:/docker-entrypoint-initdb.d/schema_initialisation.sql
    command:
      - --default-time-zone=Asia/Seoul
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=0
      - --slow-query-log=ON
      - --long-query-time=2

  auth_local_redis:
    platform: linux/x86_64
    image: redis:7.2.4-alpine3.19
    hostname: auth_local_redis
    container_name: auth_local_redis
    restart: always
    ports:
      - "16379:6379"
    networks:
      - backend-api-server-redis-network

networks:
  backend-api-server-redis-network:
    driver: bridge