services:
  auth_local_database:
    platform: linux/x86_64
    image: postgres:13
    hostname: auth_local_database
    container_name: auth_local_database
    restart: always
    environment:
      POSTGRES_PASSWORD: welcome
    ports:
      - "15432:5432"
    volumes:
      - ./database/schema_initialisation.sql:/docker-entrypoint-initdb.d/schema_initialisation.sql
    command:
      - postgres
      - -c
      - log_min_duration_statement=2000

  auth_local_redis:
    platform: linux/x86_64
    image: redis:7.2.4-alpine3.19
    hostname: auth_local_redis
    container_name: auth_local_redis
    restart: always
    environment:
      REDIS_PASSWORD: welcome
    ports:
      - "16379:6379"
    networks:
      - backend-api-server-redis-network
    command: ["redis-server", "--requirepass", "welcome"]

networks:
  backend-api-server-redis-network:
    driver: bridge