# develop ìš© Spring Profile
spring:
  config:
    activate:
      on-profile: develop
  data:
    redis:
      host: localhost
      port: 16379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    #    TODO: Secret Values
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-migration-naming: true
    schemas: auth_1
    default-schema: auth_1
server:
  port: 3001