# develop ìš© Spring Profile
spring:
  config:
    activate:
      on-profile: develop
  data:
    redis:
      host: localhost
      port: 16379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
