spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      test:
        - common
      develop:
        - common

---
# 공통
spring:
  config:
    activate:
      on-profile: common
  flyway:
    enabled: false
server:
  port: 3001

springdoc:
  swagger-ui:
    path: /docs