spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: localhost
      port: 16379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-migration-naming: true
    schemas: auth_1
    default-schema: auth_1
server:
  port: 3001