services:
  content_local_database:
    platform: linux/x86_64
    image: postgres:13
    hostname: content_local_database
    container_name: content_local_database
    restart: always
    environment:
      POSTGRES_PASSWORD: welcome
    ports:
      - "25432:5432"
    volumes:
      - ./database/schema_initialisation.sql:/docker-entrypoint-initdb.d/schema_initialisation.sql
    command:
      - postgres
      - -c
      - log_min_duration_statement=2000