# develop ìš© Spring Profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgresql
    password: Dhgkswls707!
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    validate-migration-naming: true
server:
  port: 3003