# develop 용 Spring Profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
    # TODO: develop 환경
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    validate-migration-naming: true
server:
  port: 3003