name: Push Workflow (develop)

on:
  push:
    branches:
      - develop

jobs:
  push_develop_package_services:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v4

      # Dockerhub 로그인
#      - name: Log in to Dockerhub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      # Github Registry 로그인
      - name: Log in to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

      # JDK 설정
      - name: Setup JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'

      # Gradle 캐시 설정
      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # 각 모듈 패키징 작업
      - name: Service auth package
        uses: ./.github/actions/package
        with:
          target: auth
      - name: Service content package
        uses: ./.github/actions/package
        with:
          target: content
      - name: Service user package
        uses: ./.github/actions/package
        with:
          target: user
      - name: Service gateway package
        uses: ./.github/actions/package
        with:
          target: gateway

      # 각 모듈 Docker 이미지 생성 및 Dockerhub 배포
      # TODO: Github Registry 로 변경
      - name: Service auth Deploy
        uses: ./.github/actions/deploy
        with:
          target: auth
      - name: Service content Deploy
        uses: ./.github/actions/deploy
        with:
          target: content
      - name: Service user Deploy
        uses: ./.github/actions/deploy
        with:
          target: user
      - name: Service gateway Deploy
        uses: ./.github/actions/deploy
        with:
          target: gateway

      # TODO: EC2 접근 후 각 서비스 업데이트